name: Node.js CI

on:
  release:
    types: [published]
  push:
    branches: [main]
  pull_request:
    branches: [main, dependency_updates]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install --immutable
      - run: yarn run check-types
      - run: yarn run check-format
      - run: yarn run lint
      - run: yarn run test:coverage
      - run: yarn run build
      - name: Code coverage
        if: matrix.node-version == '16.x'
        uses: codecov/codecov-action@v3.1.0
      - name: Generate documentation
        if: matrix.node-version == '16.x'
        run: yarn run build-doc
      - name: Deploy documentation to github pages
        if: ${{ matrix.node-version == '16.x' && github.event_name == 'release' }}
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs # The folder the action should deploy.
