import { useRef } from "react";
import { Meta, Story } from "@storybook/react/types-6-0";
import LineChart, { Props } from "../components/Charts/LineChart";

type MainProps = Omit<Props, "svgContainerRef">;

const meta: Meta = {
  title: "Charts/LineChart",
  component: LineChart,
};

const Template: Story<MainProps> = (args) => {
  const ref = useRef<HTMLDivElement>(null);
  return <LineChart {...args} svgContainerRef={ref} />;
};

export const Primary = Template.bind({});
const props: MainProps = {
  showLevel: false,
  data: [
    {
      label: "Nasjonalt",
      year: 2017,
      value: 0.35,
      id: 1,
      ind_id: "barnediabetes_hba1c_ge_9",
      unit_level: "nation",
      unit_name: "Nasjonalt",
      orgnr: 1,
      denominator: 2775,
      var: 0.1081,
      level: "L",
      level_direction: 0,
      dg: null,
      include: 1,
      type: "andel",
      delivery_time: new Date("October 13, 2014 11:13:00"),
      delivery_latest_affirm: new Date("October 13, 2019 11:13:00"),
    },
    {
      label: "Nasjonalt",
      year: 2018,
      value: 0.5,
      id: 1006,
      ind_id: "barnediabetes_hba1c_ge_9",
      unit_level: "nation",
      unit_name: "Nasjonalt",
      orgnr: 1,
      denominator: 2775,
      var: 0.1081,
      level: "L",
      level_direction: 0,
      dg: null,
      include: 1,
      type: "andel",
      delivery_time: new Date("October 13, 2014 11:13:00"),
      delivery_latest_affirm: new Date("October 13, 2019 11:13:00"),
    },
    {
      label: "Nasjonalt",
      year: 2019,
      value: 0.75,
      id: 1006,
      ind_id: "barnediabetes_hba1c_ge_9",
      unit_level: "nation",
      unit_name: "Nasjonalt",
      orgnr: 1,

      denominator: 2775,
      var: 0.1081,
      level: "L",
      level_direction: 0,
      dg: null,
      include: 1,
      type: "andel",
      delivery_time: new Date("October 13, 2014 11:13:00"),
      delivery_latest_affirm: new Date("October 13, 2019 11:13:00"),
    },
    {
      label: "Nasjonalt",
      year: 2020,
      value: 0.4,
      id: 1006,
      ind_id: "barnediabetes_hba1c_ge_9",
      unit_level: "nation",
      unit_name: "Nasjonalt",
      orgnr: 1,

      denominator: 2775,
      var: 0.1081,
      level: "L",
      level_direction: 0,
      dg: null,
      include: 1,
      type: "andel",
      delivery_time: new Date("October 13, 2014 11:13:00"),
      delivery_latest_affirm: new Date("October 13, 2019 11:13:00"),
    },

    {
      label: "Ahus",
      year: 2017,
      value: 0.45,
      id: 1006,
      ind_id: "barnediabetes_hba1c_ge_9",
      unit_level: "nation",
      unit_name: "Nasjonalt",
      orgnr: 1,

      denominator: 2775,
      var: 0.1081,
      level: "L",
      level_direction: 0,
      dg: null,
      include: 1,
      type: "andel",
      delivery_time: new Date("October 13, 2014 11:13:00"),
      delivery_latest_affirm: new Date("October 13, 2019 11:13:00"),
    },
    {
      label: "Ahus",
      year: 2018,
      value: 0.8,
      id: 1006,
      ind_id: "barnediabetes_hba1c_ge_9",
      unit_level: "nation",
      unit_name: "Nasjonalt",
      orgnr: 1,

      denominator: 2775,
      var: 0.1081,
      level: "L",
      level_direction: 0,
      dg: null,
      include: 1,
      type: "andel",
      delivery_time: new Date("October 13, 2014 11:13:00"),
      delivery_latest_affirm: new Date("October 13, 2019 11:13:00"),
    },
    {
      label: "Ahus",
      year: 2019,
      value: 0.6,
      id: 1006,
      ind_id: "barnediabetes_hba1c_ge_9",
      unit_level: "nation",
      unit_name: "Nasjonalt",
      orgnr: 1,

      denominator: 2775,
      var: 0.1081,
      level: "L",
      level_direction: 0,
      dg: null,
      include: 1,
      type: "andel",
      delivery_time: new Date("October 13, 2014 11:13:00"),
      delivery_latest_affirm: new Date("October 13, 2019 11:13:00"),
    },
    {
      label: "Ahus",
      year: 2020,
      value: 0.7,
      id: 1006,
      ind_id: "barnediabetes_hba1c_ge_9",
      unit_level: "nation",
      unit_name: "Nasjonalt",
      orgnr: 1,

      denominator: 2775,
      var: 0.1081,
      level: "L",
      level_direction: 0,
      dg: null,
      include: 1,
      type: "andel",
      delivery_time: new Date("October 13, 2014 11:13:00"),
      delivery_latest_affirm: new Date("October 13, 2019 11:13:00"),
    },

    {
      label: "UNN",
      year: 2017,
      value: 0.45,
      id: 1006,
      ind_id: "barnediabetes_hba1c_ge_9",
      unit_level: "nation",
      unit_name: "Nasjonalt",
      orgnr: 1,

      denominator: 2775,
      var: 0.1081,
      level: "L",
      level_direction: 0,
      dg: null,
      include: 1,
      type: "andel",
      delivery_time: new Date("October 13, 2014 11:13:00"),
      delivery_latest_affirm: new Date("October 13, 2019 11:13:00"),
    },
    {
      label: "UNN",
      year: 2018,
      value: 0.7,
      id: 1006,
      ind_id: "barnediabetes_hba1c_ge_9",
      unit_level: "nation",
      unit_name: "Nasjonalt",
      orgnr: 1,

      denominator: 2775,
      var: 0.1081,
      level: "L",
      level_direction: 0,
      dg: null,
      include: 1,
      type: "andel",
      delivery_time: new Date("October 13, 2014 11:13:00"),
      delivery_latest_affirm: new Date("October 13, 2019 11:13:00"),
    },
    {
      label: "UNN",
      year: 2019,
      value: 0.6,
      id: 1006,
      ind_id: "barnediabetes_hba1c_ge_9",
      unit_level: "nation",
      unit_name: "Nasjonalt",
      orgnr: 1,

      denominator: 2775,
      var: 0.1081,
      level: "L",
      level_direction: 0,
      dg: null,
      include: 1,
      type: "andel",
      delivery_time: new Date("October 13, 2014 11:13:00"),
      delivery_latest_affirm: new Date("October 13, 2019 11:13:00"),
    },
    {
      label: "UNN",
      year: 2020,
      value: 0.8,
      id: 1006,
      ind_id: "barnediabetes_hba1c_ge_9",
      unit_level: "nation",
      unit_name: "Nasjonalt",
      orgnr: 1,

      denominator: 2775,
      var: 0.1081,
      level: "L",
      level_direction: 0,
      dg: null,
      include: 1,
      type: "andel",
      delivery_time: new Date("October 13, 2014 11:13:00"),
      delivery_latest_affirm: new Date("October 13, 2019 11:13:00"),
    },
  ],
  levels: [
    { level: "high", start: 1, end: 0.9 },
    { level: "mid", start: 0.9, end: 0.5 },
    { level: "low", start: 0.5, end: 0 },
  ],
  tickformat: undefined,
};
Primary.args = props;

export default meta;
