name: Deploy app to AWS
on:
  release:
    types: [published]
  push:
    branches: [master]
  pull_request:
    branches: [master, dependabot_updates]

jobs:
  deploy_to_S3:
    name: Deploy app to S3
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: 'eu-west-1'
    steps:
      - name: Set release variables
        if: github.event_name == 'release'
        run: |
          echo "api=https://dc9yut6ftb9m1.cloudfront.net" >> $GITHUB_ENV
          echo "s3_bucket=s3://skde.org/kvalitetsregistre" >> $GITHUB_ENV
      - name: Set QA variables
        if: github.event_name == 'push'
        run: |
          echo "api=https://d2mrl4o83i9jyx.cloudfront.net" >> $GITHUB_ENV
          echo "s3_bucket=s3://qa.skde.org/kvalitetsregistre" >> $GITHUB_ENV
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build package
        env:
          REACT_APP_API_HOST: ${{ env.api }}
        run: npm install && npm run build
      - name: Sync to S3 bucket
        if: github.event_name != 'pull_request'
        run: |
          aws s3 sync build ${{ env.s3_bucket }} --delete --cache-control "public, max-age=31536000"
          aws s3 cp build/asset-manifest.json ${{ env.s3_bucket }}/asset-manifest.json --cache-control "public, max-age=1, s-maxage=1"
          aws s3 cp build/index.html ${{ env.s3_bucket }}/index.html --cache-control "public, max-age=1, s-maxage=1"
      - name: Build and sync to verify page
        if: github.event_name == 'release'
        env:
          REACT_APP_API_HOST: https://d25giyx4mh4r8t.cloudfront.net
        run: |
          npm install && npm run build
          aws s3 sync build s3://verify.skde.org/kvalitetsregistre --delete --cache-control "public, max-age=31536000"
          aws s3 cp build/asset-manifest.json s3://verify.skde.org/kvalitetsregistre/asset-manifest.json --cache-control "public, max-age=1, s-maxage=1"
          aws s3 cp build/index.html s3://verify.skde.org/kvalitetsregistre/index.html --cache-control "public, max-age=1, s-maxage=1"
